### ISSUE TITLE
Shared secret based grants

### ISSUE THREAD

**Issue by gregdhill** [monax/hoard#16]
## Primary
Currently, Hoard allows the storage of a reference blob but does not yet facilitate the sharing of data through grants - an encrypted reference. The secret key (a file's original SHA256 digest), should be able to be securely communicated in some manner, perhaps through a contract that queries the hoard daemon which should mirror the preexisting GRPC interface.

## Secondary
It may prove beneficial to use the same elliptic curves as currently employed by Burrow for grant sharing.

**Comment by compleatang** [comment]
Note from AN-233

```
Using AES, can be building block for sharing via vault or ECDH where the shared secret is derived from key pairs
```

**Comment by compleatang** [comment]
ECDH Grants (formerly AN-234)

Establish a shared secret using nacl box: https://godoc.org/golang.org/x/crypto/nacl/box#GenerateKey which uses Elliptic Curve Diffie Hellman to get shared secret.

Uses Curve25519, so if we want to use underlying ed25519 keys we need some key derivation. Also we may want to generate ephemeral keys to do sharing for perfect forward secrecy: https://en.wikipedia.org/wiki/Station-to-Station_protocol

**Comment by gregdhill** [comment]
* CLI tooling for secrets
* OpenPGP secrets access (https://github.com/thwarted/quickpgp may be helpful)
* Secrets store outside of config - env vars, vault, GPG

**Comment by gregdhill** [comment]
This is mostly done, I'm splitting the remaining enhancements into separate tickets so I can close this.
